---
use_oracle_java: False
oracle_java_dir_source: '/usr/local/src'

oracle_java_set_as_default: yes

oracle_java_version: 8
oracle_java_version_string: "1.{{ oracle_java_version }}.0_{{ oracle_java_version_update }}"
oracle_java_ansible_arch_mappings:
  x86_64: x64
  i386: i586

oracle_java_home: "/usr/java/jdk1.{{ oracle_java_version }}.0_{{ oracle_java_version_update }}"

oracle_java_os_supported: yes
oracle_java_rpm_validate_certs: yes

oracle_java_download_timeout: 120